# Generated by Django 4.1.7 on 2023-04-14 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0002_braid_description_crochet_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='natural_hair',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=7),
        ),
        migrations.AlterField(
            model_name='twist',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=7),
        ),
    ]
