# Generated by Django 4.1.7 on 2023-04-14 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0004_alter_braid_price_alter_crochet_price_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='braid',
            old_name='duration',
            new_name='caption',
        ),
        migrations.AlterField(
            model_name='braid',
            name='description',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='crochet',
            name='description',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='natural_hair',
            name='description',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='other_service',
            name='description',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='twist',
            name='description',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
