# Generated by Django 4.1.7 on 2023-04-14 22:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0005_rename_duration_braid_caption_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='crochet',
            old_name='duration',
            new_name='caption',
        ),
        migrations.RenameField(
            model_name='natural_hair',
            old_name='duration',
            new_name='caption',
        ),
        migrations.RenameField(
            model_name='other_service',
            old_name='duration',
            new_name='caption',
        ),
        migrations.RenameField(
            model_name='twist',
            old_name='duration',
            new_name='caption',
        ),
    ]
