# Generated by Django 4.1.7 on 2023-04-14 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0006_rename_duration_crochet_caption_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='braid',
            name='description',
        ),
        migrations.RemoveField(
            model_name='crochet',
            name='description',
        ),
        migrations.RemoveField(
            model_name='natural_hair',
            name='description',
        ),
        migrations.RemoveField(
            model_name='other_service',
            name='description',
        ),
        migrations.RemoveField(
            model_name='twist',
            name='description',
        ),
        migrations.AddField(
            model_name='braid',
            name='duration',
            field=models.DurationField(default='00:00'),
        ),
        migrations.AddField(
            model_name='crochet',
            name='duration',
            field=models.DurationField(default='00:00'),
        ),
        migrations.AddField(
            model_name='natural_hair',
            name='duration',
            field=models.DurationField(default='00:00'),
        ),
        migrations.AddField(
            model_name='other_service',
            name='duration',
            field=models.DurationField(default='00:00'),
        ),
        migrations.AddField(
            model_name='twist',
            name='duration',
            field=models.DurationField(default='00:00'),
        ),
        migrations.AlterField(
            model_name='braid',
            name='caption',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='crochet',
            name='caption',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='natural_hair',
            name='caption',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='other_service',
            name='caption',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='twist',
            name='caption',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
