# Generated by Django 4.1.7 on 2023-04-28 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0002_braid_caption_crochet_caption_natural_hair_caption_and_more'),
        ('service', '0007_remove_braid_description_remove_crochet_description_and_more'),
    ]

    operations = [
    ]
