# Generated by Django 4.1.7 on 2023-04-14 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0008_remove_braid_caption_remove_braid_duration_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='braid',
            name='caption',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name='braid',
            name='duration',
            field=models.DurationField(default='00:00'),
        ),
        migrations.AddField(
            model_name='crochet',
            name='caption',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name='crochet',
            name='duration',
            field=models.DurationField(default='00:00'),
        ),
        migrations.AddField(
            model_name='natural_hair',
            name='caption',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name='natural_hair',
            name='duration',
            field=models.DurationField(default='00:00'),
        ),
        migrations.AddField(
            model_name='other_service',
            name='caption',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name='other_service',
            name='duration',
            field=models.DurationField(default='00:00'),
        ),
        migrations.AddField(
            model_name='twist',
            name='caption',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name='twist',
            name='duration',
            field=models.DurationField(default='00:00'),
        ),
    ]
