# Generated by Django 4.1.7 on 2023-03-11 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='price',
            field=models.IntegerField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='time',
            field=models.IntegerField(choices=[('8 AM', '8 AM'), ('2 PM', '2 PM')], default='8 AM', max_length=10),
        ),
    ]
