# Generated by Django 4.1.7 on 2023-04-28 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_alter_appointment_deposit_alter_appointment_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='name',
            field=models.CharField(blank=True, max_length=225, null=True),
        ),
    ]
